export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const SIGN_SUCCESS="SIGN_SUCCESS"
export const SIGN_REQUEST="SIGN_REQUEST"
export const SIGN_FAILURE="SIGN_FAILURE";

